# Importing of Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing dataset

In [2]:
df = pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
df.isnull().any() # null values are present

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

In [4]:
type(df)

pandas.core.frame.DataFrame

# Handling Missing Values

In [5]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
df[df['Age'].isnull()].index.tolist() # to find the index

[6]

In [7]:
df[df['Salary'].isnull()].index.tolist()

[4]

## 1. For categorical values we can use mode

### 2. For continuous values we can use mean(normal distribution) or median(skew distribution) for replacement

## 3. Less than 5 percent of dataset null values remove them

In [9]:
from IPython.display import Image
Image(url= "skew.png", width=600, height=600)

In [13]:
df.Salary.mean()

63777.777777777774

In [14]:
df.Salary.median()

62388.88888888889

In [15]:
df.Age.mean()

38.77777777777778

In [16]:
df.Age.median()

38.388888888888886

In [11]:
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain   NaN  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [12]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [17]:
df.Age = df.Age.round()
df

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  39.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

# Separating Independent and Dependent Variables

In [21]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [22]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [23]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [25]:
X.ndim

2

In [26]:
y.ndim

1

# Encoding Categorical Text Variables

In [27]:
df['Country'].value_counts()

France     4
Spain      3
Germany    3
Name: Country, dtype: int64

In [28]:
X.shape

(10, 3)

### Nominal(male,female) and Ordinal(good,bad) variables

# OneHotEncoding - Binary Encoding

In [ ]:
## Label encoding leads to unnecessary linear relations
## So we have to do One hot encoding 
# Dummy variable trap arises 
## The Dummy Variable Trap occurs when two or more dummy variables created by one-hot encoding are highly correlated (multi-collinear). 
# This means that one variable can be predicted from the others, 
# making it difficult to interpret predicted coefficient variables in regression models.

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [33]:
ct = ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough")
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [34]:
X = X[:,1:]
X

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

# for classification no need to remove dummy variables

In [36]:
from sklearn.preprocessing import LabelEncoder

In [42]:
lb = LabelEncoder()
y = lb.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

# Splitting into Training and Test data

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [45]:
X_train

array([[0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 44.0, 72000.0]], dtype=object)

In [46]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [47]:
X_train.shape

(8, 4)

In [48]:
X_test.shape

(2, 4)

In [49]:
y_train.shape

(8,)

In [50]:
y_test.shape

(2,)