In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [6]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
type(z)

numpy.ndarray

In [8]:
z.ndim

1

In [9]:
y = np.array([1,2,4.5,6,78])
y

array([ 1. ,  2. ,  4.5,  6. , 78. ])

In [10]:
type(y)

numpy.ndarray

In [12]:
x = np.array(["23",4,5,6])
type(x)
x

array(['23', '4', '5', '6'], dtype='<U2')

In [13]:
y.shape

(5,)

In [23]:
z = np.array([[2,5,7,8],[4,5,6,7]])
z.shape
z

array([[2, 5, 7, 8],
       [4, 5, 6, 7]])

In [15]:
z

array([[2, 5, 7, 8],
       [4, 5, 6, 7]])

In [16]:
z = z.reshape(4,2)
z

array([[2, 5],
       [7, 8],
       [4, 5],
       [6, 7]])

In [17]:
z = z.reshape(1,8)
z

array([[2, 5, 7, 8, 4, 5, 6, 7]])

In [18]:
z = z.reshape(1,8,1)
z

array([[[2],
        [5],
        [7],
        [8],
        [4],
        [5],
        [6],
        [7]]])

In [19]:
z = z.reshape(2,2,2)
z

array([[[2, 5],
        [7, 8]],

       [[4, 5],
        [6, 7]]])

In [20]:
z = z.reshape(1,4,2)
z

array([[[2, 5],
        [7, 8],
        [4, 5],
        [6, 7]]])

In [21]:
z = z.reshape(8,1,1,1)
z

array([[[[2]]],


       [[[5]]],


       [[[7]]],


       [[[8]]],


       [[[4]]],


       [[[5]]],


       [[[6]]],


       [[[7]]]])

In [22]:
z = z.reshape(8,)
z

array([2, 5, 7, 8, 4, 5, 6, 7])

In [24]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
z[0][1]

2

In [26]:
z[[0]]

array([[1, 2, 3]])

In [27]:
z[[1]]

array([[4, 5, 6]])

In [28]:
z[1:,1:]

array([[5, 6],
       [8, 9]])

In [29]:
z[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [30]:
z[0:1,1:]

array([[2, 3]])

In [31]:
z[0:2,2]

array([3, 6])

In [32]:
z[0:2,2:]

array([[3],
       [6]])

In [33]:
z[1:,1:2]

array([[5],
       [8]])

In [34]:
p = np.linspace(0,10,20)#equally spaced values between 0 and 10
p

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [35]:
p.max() # to get max value

10.0

In [36]:
p.min() # to get minimum value

0.0

In [37]:
p.argmax() # index of maximum value

19

In [38]:
p.argmin()

0

In [45]:
np.where(p==10.0) #using where method

(array([19], dtype=int64),)

In [43]:
s = np.arange(1000,1500,20) # an array within range with step size
s

array([1000, 1020, 1040, 1060, 1080, 1100, 1120, 1140, 1160, 1180, 1200,
       1220, 1240, 1260, 1280, 1300, 1320, 1340, 1360, 1380, 1400, 1420,
       1440, 1460, 1480])

In [44]:
c = s + s # element by element addition
c

array([2000, 2040, 2080, 2120, 2160, 2200, 2240, 2280, 2320, 2360, 2400,
       2440, 2480, 2520, 2560, 2600, 2640, 2680, 2720, 2760, 2800, 2840,
       2880, 2920, 2960])

In [46]:
c = c<2500
c

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [47]:
dir(c)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [48]:
c.size

25

In [49]:
import datetime

d=datetime.date(2016,7,24)

print(d)

2016-07-24


In [50]:
import datetime

d=datetime.date(2017,6,18)

print(d)

2017-06-18


In [51]:
tday=datetime.date.today()

tday.month

6

In [52]:
n = np.array((2,3,4,6,7))
n

array([2, 3, 4, 6, 7])

In [53]:
n[2]

4

In [54]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr1 + arr2

array([ 6,  8, 10, 12])

In [55]:
arr1 - arr2

array([-4, -4, -4, -4])

In [56]:
arr1 * arr2

array([ 5, 12, 21, 32])

In [58]:
list(arr1)

[1, 2, 3, 4]

In [59]:
a = np.full([2, 2], 67, dtype = int)
print("\nMatrix a : \n", a)
  
c = np.full([3, 3], 10.1)
print("\nMatrix c : \n", c)


Matrix a : 
 [[67 67]
 [67 67]]

Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]
